# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awVNgFBsk342yEgfnIysTlTMyretRowH
"""

list=['sam',45,65.0,'Rahul']
print(list)

list=['sam',45,65.0,'Rahul']
print(list)
print(type(list))

print(list[0])
print(list[1])
print(list[2])
print(list[3]) ## forword indexing
print("-----------------------------------------")
print(list[-1])
print(list[-2])
print(list[-3])
print(list[-4]) ##reverse indexing
print("------------------------------------------")

# "slicing in list"
list=['sam',45,65.0,'Rahul']
print(list)

list[0:2]
list[1:4]
list[2:]
list[:]
list[-1::-1]
list[3][2]

# "lsit mutable deta type"
list=['sam',45,65.0,'Rahul']
list[3]="python"
print(list)

# "loop in list"
list=['sam',45,65.0,'Rahul']
for i in list:
  print(i,end=" ")

list=['sam',45,65.0,'Rahul']
for i in range(len(list)):
  print(i)

list=['sam',45,65.0,'Rahul']
for i in range(len(list)):
  print(list[i])

list=['sam',45,65.0,'Rahul']
for i in range(len(list)):
  print(list[i],end=" ")

##properties of list"
# 1.concatenation

a=[1,2,3]
b=[4,5,6]
c=a+b
c

#replication

a=[1,2,3]
a*3

# fuctions in list

# 1. len()-----> it will return length of a list
list=['sam',45,65.0,'Rahul']
print(len(list))

# 2.index fuction------> it will return indexing of a element
list=['sam',45,65.0,'Rahul']
list.index('Rahul')

# 3.append----------> it will add in element in the last indexing
a=[]
a.append('maths')
print(a)
a.append('physics')
print(a)
a.append("science")
print(a)

# 4.insert -------------------> it will add an element at any indexing of a list .
list=['sam',45,65.0,'Rahul']
print(a)
a.insert(1,900)
print(a)

# pop-------------> it will remove last element in list
list=['sam',45,65.0,'Rahul']
list.pop()
print(list)

# remove --------------->  it will remove element from an list.
list=['sam',45,65.0,'Rahul']
print(list)
list.remove(45)
print(list)

# reverse--------------> it will reverse in list .
list=['sam',45,65.0,'Rahul']
print(list)
list.reverse()
print(list)

# 8.sort----------------> it will change the value accending orders .
list=['sam',45,65.0,'Rahul']
print(list)
list.sort()
print(list)
list.reverse()
print(list)

# count

a=[]
size=int(input("enter the size:-"))
for i in range(size):
  val=int(input("enter the number:"))
  a.append(val)
print(a)
sum=0
for i in range(len(a)):
  sum=sum+a[i]
print("total number is ",sum)

# """max"""
a=[]
size=int(input("enter size:-"))
for i in range(size):
  val=int(input("enter number:"))
  a.append(val)
print(a)
max=a[0]
for i in range(len(a)):
  if a[i] > max:
    max=a[i]
print("total max is:- ",max)

a=[]
size=int(input("enter size:-"))
for i in range(size):
  val=int(input("enter number"))
  a.append(val)
print(a)

total_sum=0
for i in range(1,size+2):
  total_sum=total_sum+i
print("total=",total_sum)
list_sum=0
for n in a:
  list_sum=list_sum+n
print(list_sum)

missing=total_sum - list_sum
print("missing number:-",missing)

a=[1,2,3,4]
b=[3,4,5,6]
c=[]
for i in a:
  if i in b:
    c.append(i)
  print(c)

a=[1,2,2,2,2,3,2,3,3,2,3]
b=[]
for i in a:
  for i in b:
    b.append(i)
  print(a)
  print(b)

a=[]
size=int(input("enter size:-"))
for i in range(size):
  val=int(input("enter the number:"))
  a.append(val)
print(a)
sum=0
for i in range(len(a)):
  sum=sum+a[i]
print("total sum",sum)

list=[]
size=int(input("enter the number"))
for i in range(size):
  val=int(input("enter the number:"))
  list.append(val)
if list==list[-1::-1]:
  print("palimdrom")
else:
  print("not")

# "list comprehension"
# list comprehension in python provide a concise way to create lists.
# the are more readable and efficient than traditional for loop .
# syntax:
# [expression for item in itreable if condition]

# write a program who print list of squares!

a=[1,2,3,4]
b=[]
for i in range(1,len(a)+1):
  b.append(i**2)
print(a)
print(b)

# using the list comprehension .

square=[x**2 for x in range(1,5)]
print(square)

square=[x**3 for x in range(1,5)]
print(square)

square=[x**4 for x in range(1,5)]
print(square)

x_vals=[1,2,3]
y_vals=[4,5,6]
pair=[(x,y) for x in x_vals for y in y_vals]
pair

# multiplication table

a=[f"{i}*{j}={i*j}"for i in range(1,3)for j in range(1,11)]
a

# cartesion product with condition

x_val=[1,2,3]
y_val=[3,4,5]
prod=[(x,y) for x in x_val for y in y_val if x+y>5]
prod

x_val=[1,2,3]
y_val=[3,4,5]
prod=[(x,y) for x in x_val for y in y_val if x+y>5]
prod

x_val=[1,2,3]
y_val=[3,4,5]
prod=[(x,y) for x in x_val for y in y_val if x%y==0]
prod

a=[i for i in range(1,11) if i%2==0]
a

a=[i for i in range(1,11)if i%2!=0]
a

a=[i for i in range(1,10) if i**2>20]
a

# convert all string in upoer case.

names=["sam","rohit","ankit"]
upper_names=[i.upper()for i in names]
print(upper_names)

a=["charchil","divya",45,78.92,256,"rahul"]
b=[i for i in a if type(i)==str]
print(b)

a="i love python"
c='aeiou'
b=[ i for i in a if i in c]
print(b)

a=[i for i in range(1,51) if i%3==0 and i%5!=0]
a

a = ["sam", "raj", 'rohit']
m = [a[i][0] for i in range(len(a))]
print(m)

shop=["pen","notebook","pizza","icecream","vadapav","football","jeans","shoes","shirts"]
statinory=["pen","notebook"]
bakey=["icecream","pizza","vadapav"]
cloths=["jeans","shoes","shirts"]
print(statinory)

y_val = [(x_val,y_val) x**2 for x in x_val]
print(y_val)

b=[(x,x**2) for x in range(1,6)]
b

a=['9567465691','8756736723','2345','9579']
valid=[i for i in a if len(i)==10]
valid

a = ["py@thon", "d#ata","sci!ence"]
b = "@#!"

valid = [i for i in a if a!=b]

print(valid)

a=['python','data','science','machine','ai','9579']

max_len = max(len(i) for i in a)
valid = [i for i in a if len(i) == max_len]
print(valid)

a = ['python', 'data', 'science', 'machine', 'ai', '9579']
a.sort()
print(a)
a.reverse()
print(a)
b=a[:3]
print(b)

num=153
temp=num
sum=0
while num>0:
  r=num%10                  153=3 sum=0 sum=0+3**3=27 num=153//10=15
                            15=5 sum=27 sum=27+5**3=152 num=15=
                            1 sum=152 sum=152+1**3=153 num=1=1
  sum=sum+(r**3)
  num=num//10
if temp==sum:
  print("armstrong ")
else:
  print("not")

num=145
temp=num
sum_of_factorials = 0  # Initialize sum_of_factorials
while num>0:
  digit = num % 10  # Get the last digit
  fact=1
  for i in range(1, digit + 1): # Calculate factorial of the digit
    fact = fact * i
  sum_of_factorials = sum_of_factorials + fact  # Add factorial to the sum
  num=num//10 # Remove the last digit
if sum_of_factorials == temp:
  print("strong number")
else:
  print("not")

a="Python is fun"
b=[i for i in a [::-1]]
b

a="Python is fun"
b=[i for i in a.split()]
b

b=[(i,i**2) for i in range(1,51) if i%4==0]
b

a=[[1,2],[3,4],[5,6]]
b=[x for sublist in a for x in sublist]
b

sentence = "madam teaches malayalam in noon"
palindromes = [word for word in sentence.split() if word == word[::-1]]
print(palindromes)

sentence = "Python is fun to learn"
word_length = {word: len(word) for word in sentence.split()}
print(word_length)

a=["hii how","you doing"]
  vowel="aeiou"
  for i in a:
    for j in i:
      if j in vowel:
        print(j,end="")

a=[[1,2],[3,4],[5,6]]
a.extend([6,7])

